apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
        - name: python-app
          image: 822626997628.dkr.ecr.ap-south-1.amazonaws.com/python-flask-demo:14 # {"$imagepolicy": "flux-system:python-demo-policy"}
